import type { Car } from '@/types'

export const MOCK_CARS: Car[] = [
  {
    id: '1',
    name: 'Dacia Sandero Stepway 2024',
    brand: 'Dacia',
    model: 'Sandero Stepway',
    year: 2024,
    category: 'economique',
    transmission: 'automatic',
    fuel_type: 'essence',
    seats: 5,
    price_per_day: 4500,
    deposit_amount: null,
    features: ['climatisation', 'bluetooth', 'aide_stationnement', 'abs', 'esp'],
    images: [],
    thumbnail_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Seat Ibiza 2025',
    brand: 'Seat',
    model: 'Ibiza',
    year: 2025,
    category: 'economique',
    transmission: 'automatic',
    fuel_type: 'essence',
    seats: 5,
    price_per_day: 5000,
    deposit_amount: null,
    features: ['climatisation', 'bluetooth', 'camera_recul', 'abs', 'esp'],
    images: [],
    thumbnail_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Volkswagen Taigo 2024',
    brand: 'Volkswagen',
    model: 'Taigo',
    year: 2024,
    category: 'suv',
    transmission: 'automatic',
    fuel_type: 'essence',
    seats: 5,
    price_per_day: 7000,
    deposit_amount: null,
    features: ['climatisation', 'bluetooth', 'gps', 'camera_recul', 'abs', 'esp'],
    images: [],
    thumbnail_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Audi Q3 2024',
    brand: 'Audi',
    model: 'Q3',
    year: 2024,
    category: 'premium',
    transmission: 'automatic',
    fuel_type: 'essence',
    seats: 5,
    price_per_day: 9500,
    deposit_amount: null,
    features: ['climatisation', 'bluetooth', 'gps', 'camera_recul', 'toit_ouvrant', 'abs', 'esp', 'sieges_chauffants'],
    images: [],
    thumbnail_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Range Rover Evoque 2024',
    brand: 'Land Rover',
    model: 'Range Rover Evoque',
    year: 2024,
    category: 'luxe',
    transmission: 'automatic',
    fuel_type: 'essence',
    seats: 5,
    price_per_day: 15000,
    deposit_amount: null,
    features: ['climatisation', 'bluetooth', 'gps', 'camera_360', 'toit_ouvrant', 'abs', 'esp', 'sieges_chauffants'],
    images: [],
    thumbnail_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Porsche Macan 2024',
    brand: 'Porsche',
    model: 'Macan',
    year: 2024,
    category: 'luxe',
    transmission: 'automatic',
    fuel_type: 'essence',
    seats: 5,
    price_per_day: 20000,
    deposit_amount: null,
    features: ['climatisation', 'bluetooth', 'gps', 'camera_360', 'toit_ouvrant', 'abs', 'esp', 'sieges_chauffants', 'pack_sport'],
    images: [],
    thumbnail_url: null,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export function isMockMode(): boolean {
  if (process.env.NEXT_PUBLIC_USE_MOCK === 'true') return true
  return (
    !process.env.NEXT_PUBLIC_SUPABASE_URL ||
    process.env.NEXT_PUBLIC_SUPABASE_URL.includes('VOTRE_PROJECT_ID')
  )
}
